name: category_links
version: 2.0.1
description: category_links application that uses dartling for its model.
author: Dzenan Ridjanovic
homepage: http://ondart.me/
environment:
  sdk: '>=1.9.3 <2.0.0'
dependencies:
  browser: any
  dartling: any
  dartling_default_app: any
  