name: default_project
version: 2.0.1
description: default_project application that uses dartling for its model.
author: Dzenan Ridjanovic
homepage: http://ondart.me/
documentation:
environment:
  sdk: '>=1.9.3 <2.0.0'
dependencies:
  browser: any
  dartling: any
  dartling_default_app: any
  